### ISSUE TITLE
Is it possible to provide the example for ros::Subscriber of detections_pub_ in face_detector?

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [Kukanani/vision_msgs_examples#6]
Hi
Do you think it's making sense to have an example for the Subscriber of the vision_msgs::Detection2DArray?
I'd like to implement an robot motion control based on the 2D detection result in ROS2 node and wondering how to achieve this goal via subscribng the topic from the Publisher of vision_msgs::Detection2DArray.

**Comment by Kukanani** [comment]
Thanks for the issue. This repo was originally designed to show examples of how to fill and publish `vision_msgs`, not so much for how to subscribe to them. Once the message is published, it should be fairly straightforward to subscribe to the message and access the different fields within it. Of course, a lot of the code will depend on if you are using Python or C++, and exactly what fields of the result you are interested in reading/using.

For these reasons, it doesn't seem worth the effort to me an example in this repository. But if you make a publicly-available example of a subscriber to this message, please feel free to make a pull request here.
